function dropRequireCache(requireFunc, filename) {
    var module = requireFunc.cache[filename];
    if (module) {
        if (module.parent) {
            if (module.parent.children) {
                var moduleIndex = module.parent.children.indexOf(module);
                if (moduleIndex !== -1) {
                    module.parent.children.splice(moduleIndex, 1);
                }
            }
            delete module.parent;
        }
        delete module.children;
        delete requireFunc.cache[filename];
    }
};
dropRequireCache(require, require.resolve("../../../.enb/lib/bh.js"));
var BH= require("../../../.enb/lib/bh.js");
var bh = new BH();
bh.setOptions({"production":true,"responsive":true,"replacements":{"btn_color_default":"btn-default","btn_color_primary":"btn-primary","btn_color_success":"btn-success","btn_color_info":"btn-info","btn_color_warning":"btn-warning","btn_color_danger":"btn-danger","btn_color_link":"btn-link","btn_size_lg":"btn-lg","btn_size_sm":"btn-sm","btn_size_xs":"btn-xs","btn_block":"btn-block","btn_link":"btn-link","btn_state_active":"","btn_state_disabled":"","alert_color_success":"alert-success","alert_color_info":"alert-info","alert_color_warning":"alert-warning","alert_color_danger":"alert-danger","alert_dismissible":"alert-dismissible","modal__dialog":"modal-dialog","modal__dialog_size_lg":"modal-lg","modal__dialog_size_sm":"modal-sm","modal__dialog_size_xs":"modal-xs","modal__content":"modal-content","modal__body":"modal-body","modal__header":"modal-header","modal__footer":"modal-footer","input_control":"form-control","label_sr-only":"sr-only","nav-tabs__item_active":"active","tab-content__item":"tab-pane","tab-content__item_active":"in active","ul_unstyled":"list-unstyled","container":"","container_fluid_off":"container","container_fluid":"container-fluid","row__col":"","row__col_xs_1":"col-xs-1","row__col_xs_2":"col-xs-2","row__col_xs_3":"col-xs-3","row__col_xs_4":"col-xs-4","row__col_xs_5":"col-xs-5","row__col_xs_6":"col-xs-6","row__col_xs_7":"col-xs-7","row__col_xs_8":"col-xs-8","row__col_xs_9":"col-xs-9","row__col_xs_10":"col-xs-10","row__col_xs_11":"col-xs-11","row__col_xs_12":"col-xs-12","row__col_xs-clear":"","row__col_xs-offset_0":"col-xs-offset-0","row__col_xs-offset_1":"col-xs-offset-1","row__col_xs-offset_2":"col-xs-offset-2","row__col_xs-offset_3":"col-xs-offset-3","row__col_xs-offset_4":"col-xs-offset-4","row__col_xs-offset_5":"col-xs-offset-5","row__col_xs-offset_6":"col-xs-offset-6","row__col_xs-offset_7":"col-xs-offset-7","row__col_xs-offset_8":"col-xs-offset-8","row__col_xs-offset_9":"col-xs-offset-9","row__col_xs-offset_10":"col-xs-offset-10","row__col_xs-offset_11":"col-xs-offset-11","row__col_xs-offset_12":"col-xs-offset-12","row__col_xs-pull_0":"col-xs-pull-0","row__col_xs-pull_1":"col-xs-pull-1","row__col_xs-pull_2":"col-xs-pull-2","row__col_xs-pull_3":"col-xs-pull-3","row__col_xs-pull_4":"col-xs-pull-4","row__col_xs-pull_5":"col-xs-pull-5","row__col_xs-pull_6":"col-xs-pull-6","row__col_xs-pull_7":"col-xs-pull-7","row__col_xs-pull_8":"col-xs-pull-8","row__col_xs-pull_9":"col-xs-pull-9","row__col_xs-pull_10":"col-xs-pull-10","row__col_xs-pull_11":"col-xs-pull-11","row__col_xs-pull_12":"col-xs-pull-12","row__col_xs-push_0":"col-xs-push-0","row__col_xs-push_1":"col-xs-push-1","row__col_xs-push_2":"col-xs-push-2","row__col_xs-push_3":"col-xs-push-3","row__col_xs-push_4":"col-xs-push-4","row__col_xs-push_5":"col-xs-push-5","row__col_xs-push_6":"col-xs-push-6","row__col_xs-push_7":"col-xs-push-7","row__col_xs-push_8":"col-xs-push-8","row__col_xs-push_9":"col-xs-push-9","row__col_xs-push_10":"col-xs-push-10","row__col_xs-push_11":"col-xs-push-11","row__col_xs-push_12":"col-xs-push-12","row__col_sm_1":"col-sm-1","row__col_sm_2":"col-sm-2","row__col_sm_3":"col-sm-3","row__col_sm_4":"col-sm-4","row__col_sm_5":"col-sm-5","row__col_sm_6":"col-sm-6","row__col_sm_7":"col-sm-7","row__col_sm_8":"col-sm-8","row__col_sm_9":"col-sm-9","row__col_sm_10":"col-sm-10","row__col_sm_11":"col-sm-11","row__col_sm_12":"col-sm-12","row__col_sm-clear":"","row__col_sm-offset_0":"col-sm-offset-0","row__col_sm-offset_1":"col-sm-offset-1","row__col_sm-offset_2":"col-sm-offset-2","row__col_sm-offset_3":"col-sm-offset-3","row__col_sm-offset_4":"col-sm-offset-4","row__col_sm-offset_5":"col-sm-offset-5","row__col_sm-offset_6":"col-sm-offset-6","row__col_sm-offset_7":"col-sm-offset-7","row__col_sm-offset_8":"col-sm-offset-8","row__col_sm-offset_9":"col-sm-offset-9","row__col_sm-offset_10":"col-sm-offset-10","row__col_sm-offset_11":"col-sm-offset-11","row__col_sm-offset_12":"col-sm-offset-12","row__col_sm-pull_0":"col-sm-pull-0","row__col_sm-pull_1":"col-sm-pull-1","row__col_sm-pull_2":"col-sm-pull-2","row__col_sm-pull_3":"col-sm-pull-3","row__col_sm-pull_4":"col-sm-pull-4","row__col_sm-pull_5":"col-sm-pull-5","row__col_sm-pull_6":"col-sm-pull-6","row__col_sm-pull_7":"col-sm-pull-7","row__col_sm-pull_8":"col-sm-pull-8","row__col_sm-pull_9":"col-sm-pull-9","row__col_sm-pull_10":"col-sm-pull-10","row__col_sm-pull_11":"col-sm-pull-11","row__col_sm-pull_12":"col-sm-pull-12","row__col_sm-push_0":"col-sm-push-0","row__col_sm-push_1":"col-sm-push-1","row__col_sm-push_2":"col-sm-push-2","row__col_sm-push_3":"col-sm-push-3","row__col_sm-push_4":"col-sm-push-4","row__col_sm-push_5":"col-sm-push-5","row__col_sm-push_6":"col-sm-push-6","row__col_sm-push_7":"col-sm-push-7","row__col_sm-push_8":"col-sm-push-8","row__col_sm-push_9":"col-sm-push-9","row__col_sm-push_10":"col-sm-push-10","row__col_sm-push_11":"col-sm-push-11","row__col_sm-push_12":"col-sm-push-12","row__col_md_1":"col-md-1","row__col_md_2":"col-md-2","row__col_md_3":"col-md-3","row__col_md_4":"col-md-4","row__col_md_5":"col-md-5","row__col_md_6":"col-md-6","row__col_md_7":"col-md-7","row__col_md_8":"col-md-8","row__col_md_9":"col-md-9","row__col_md_10":"col-md-10","row__col_md_11":"col-md-11","row__col_md_12":"col-md-12","row__col_md-clear":"","row__col_md-offset_0":"col-md-offset-0","row__col_md-offset_1":"col-md-offset-1","row__col_md-offset_2":"col-md-offset-2","row__col_md-offset_3":"col-md-offset-3","row__col_md-offset_4":"col-md-offset-4","row__col_md-offset_5":"col-md-offset-5","row__col_md-offset_6":"col-md-offset-6","row__col_md-offset_7":"col-md-offset-7","row__col_md-offset_8":"col-md-offset-8","row__col_md-offset_9":"col-md-offset-9","row__col_md-offset_10":"col-md-offset-10","row__col_md-offset_11":"col-md-offset-11","row__col_md-offset_12":"col-md-offset-12","row__col_md-pull_0":"col-md-pull-0","row__col_md-pull_1":"col-md-pull-1","row__col_md-pull_2":"col-md-pull-2","row__col_md-pull_3":"col-md-pull-3","row__col_md-pull_4":"col-md-pull-4","row__col_md-pull_5":"col-md-pull-5","row__col_md-pull_6":"col-md-pull-6","row__col_md-pull_7":"col-md-pull-7","row__col_md-pull_8":"col-md-pull-8","row__col_md-pull_9":"col-md-pull-9","row__col_md-pull_10":"col-md-pull-10","row__col_md-pull_11":"col-md-pull-11","row__col_md-pull_12":"col-md-pull-12","row__col_md-push_0":"col-md-push-0","row__col_md-push_1":"col-md-push-1","row__col_md-push_2":"col-md-push-2","row__col_md-push_3":"col-md-push-3","row__col_md-push_4":"col-md-push-4","row__col_md-push_5":"col-md-push-5","row__col_md-push_6":"col-md-push-6","row__col_md-push_7":"col-md-push-7","row__col_md-push_8":"col-md-push-8","row__col_md-push_9":"col-md-push-9","row__col_md-push_10":"col-md-push-10","row__col_md-push_11":"col-md-push-11","row__col_md-push_12":"col-md-push-12","row__col_lg_1":"col-lg-1","row__col_lg_2":"col-lg-2","row__col_lg_3":"col-lg-3","row__col_lg_4":"col-lg-4","row__col_lg_5":"col-lg-5","row__col_lg_6":"col-lg-6","row__col_lg_7":"col-lg-7","row__col_lg_8":"col-lg-8","row__col_lg_9":"col-lg-9","row__col_lg_10":"col-lg-10","row__col_lg_11":"col-lg-11","row__col_lg_12":"col-lg-12","row__col_lg-clear":"","row__col_lg-offset_0":"col-lg-offset-0","row__col_lg-offset_1":"col-lg-offset-1","row__col_lg-offset_2":"col-lg-offset-2","row__col_lg-offset_3":"col-lg-offset-3","row__col_lg-offset_4":"col-lg-offset-4","row__col_lg-offset_5":"col-lg-offset-5","row__col_lg-offset_6":"col-lg-offset-6","row__col_lg-offset_7":"col-lg-offset-7","row__col_lg-offset_8":"col-lg-offset-8","row__col_lg-offset_9":"col-lg-offset-9","row__col_lg-offset_10":"col-lg-offset-10","row__col_lg-offset_11":"col-lg-offset-11","row__col_lg-offset_12":"col-lg-offset-12","row__col_lg-pull_0":"col-lg-pull-0","row__col_lg-pull_1":"col-lg-pull-1","row__col_lg-pull_2":"col-lg-pull-2","row__col_lg-pull_3":"col-lg-pull-3","row__col_lg-pull_4":"col-lg-pull-4","row__col_lg-pull_5":"col-lg-pull-5","row__col_lg-pull_6":"col-lg-pull-6","row__col_lg-pull_7":"col-lg-pull-7","row__col_lg-pull_8":"col-lg-pull-8","row__col_lg-pull_9":"col-lg-pull-9","row__col_lg-pull_10":"col-lg-pull-10","row__col_lg-pull_11":"col-lg-pull-11","row__col_lg-pull_12":"col-lg-pull-12","row__col_lg-push_0":"col-lg-push-0","row__col_lg-push_1":"col-lg-push-1","row__col_lg-push_2":"col-lg-push-2","row__col_lg-push_3":"col-lg-push-3","row__col_lg-push_4":"col-lg-push-4","row__col_lg-push_5":"col-lg-push-5","row__col_lg-push_6":"col-lg-push-6","row__col_lg-push_7":"col-lg-push-7","row__col_lg-push_8":"col-lg-push-8","row__col_lg-push_9":"col-lg-push-9","row__col_lg-push_10":"col-lg-push-10","row__col_lg-push_11":"col-lg-push-11","row__col_lg-push_12":"col-lg-push-12","nav_type_tabs":"nav-tabs","nav_type_pills":"nav-pills","nav_orientation_stacked":"nav-stacked","nav_orientation_justified":"nav-justified","nav__item":"","nav__item_state_active":"active","nav__item_state_disabled":"disabled"},"jsAttrName":"data-bem","jsAttrScheme":"json"});

dropRequireCache(require, require.resolve("../../blocks.01-base/page/__browsehappy/page__browsehappy.bh.js"));
require("../../blocks.01-base/page/__browsehappy/page__browsehappy.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/conditional-comment/conditional-comment.bh.js"));
require("../../blocks.01-base/conditional-comment/conditional-comment.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/page/__css/page__css.bh.js"));
require("../../blocks.01-base/page/__css/page__css.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/page/__favicon/page__favicon.bh.js"));
require("../../blocks.01-base/page/__favicon/page__favicon.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/page/__head/page__head.bh.js"));
require("../../blocks.01-base/page/__head/page__head.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/page/__js/page__js.bh.js"));
require("../../blocks.01-base/page/__js/page__js.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/page/__link/page__link.bh.js"));
require("../../blocks.01-base/page/__link/page__link.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/page/__meta/page__meta.bh.js"));
require("../../blocks.01-base/page/__meta/page__meta.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/page/__noscript/page__noscript.bh.js"));
require("../../blocks.01-base/page/__noscript/page__noscript.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/ua/ua.bh.js"));
require("../../blocks.01-base/ua/ua.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/html5shiv-respond/html5shiv-respond.bh.js"));
require("../../blocks.01-base/html5shiv-respond/html5shiv-respond.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.03-fonts/fontfaceobserver/fontfaceobserver.bh.js"));
require("../../blocks.03-fonts/fontfaceobserver/fontfaceobserver.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/link/link.bh.js"));
require("../../blocks.04-common/link/link.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/to-up/to-up.bh.js"));
require("../../blocks.05-project/to-up/to-up.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/menu-bar/menu-bar.bh.js"));
require("../../blocks.04-common/menu-bar/menu-bar.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/menu-top/__link/menu-top__link.bh.js"));
require("../../blocks.05-project/menu-top/__link/menu-top__link.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/dropdown-menu/__li/dropdown-menu__li.bh.js"));
require("../../blocks.05-project/dropdown-menu/__li/dropdown-menu__li.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/img-responsive/img-responsive.bh.js"));
require("../../blocks.04-common/img-responsive/img-responsive.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/search/search.bh.js"));
require("../../blocks.04-common/search/search.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/span/span.bh.js"));
require("../../blocks.04-common/span/span.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/btn/__count/btn__count.bh.js"));
require("../../blocks.05-project/btn/__count/btn__count.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/teaser-product/__image/teaser-product__image.bh.js"));
require("../../blocks.05-project/teaser-product/__image/teaser-product__image.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/teaser-product/__title/teaser-product__title.bh.js"));
require("../../blocks.05-project/teaser-product/__title/teaser-product__title.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/product-slider-nav/__item/product-slider-nav__item.bh.js"));
require("../../blocks.05-project/product-slider-nav/__item/product-slider-nav__item.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/star-rating/star-rating.bh.js"));
require("../../blocks.04-common/star-rating/star-rating.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/star-rating/__wrap/star-rating__wrap.bh.js"));
require("../../blocks.04-common/star-rating/__wrap/star-rating__wrap.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/star-rating/__input/star-rating__input.bh.js"));
require("../../blocks.04-common/star-rating/__input/star-rating__input.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/star-rating/__icon/star-rating__icon.bh.js"));
require("../../blocks.04-common/star-rating/__icon/star-rating__icon.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/menu/__list/menu__list.bh.js"));
require("../../blocks.05-project/menu/__list/menu__list.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/menu/__item/menu__item.bh.js"));
require("../../blocks.05-project/menu/__item/menu__item.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/catalog/__list/catalog__list.bh.js"));
require("../../blocks.05-project/catalog/__list/catalog__list.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/catalog/__item/catalog__item.bh.js"));
require("../../blocks.05-project/catalog/__item/catalog__item.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/catalog/__img/catalog__img.bh.js"));
require("../../blocks.05-project/catalog/__img/catalog__img.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/comparison-btn/comparison-btn.bh.js"));
require("../../blocks.05-project/comparison-btn/comparison-btn.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/img/img.bh.js"));
require("../../blocks.04-common/img/img.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/breadcrumb/__item/breadcrumb__item.bh.js"));
require("../../blocks.04-common/breadcrumb/__item/breadcrumb__item.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/breadcrumb/__active/breadcrumb__active.bh.js"));
require("../../blocks.04-common/breadcrumb/__active/breadcrumb__active.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/comparison-list/__link/comparison-list__link.bh.js"));
require("../../blocks.05-project/comparison-list/__link/comparison-list__link.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/comparison-list/__item/comparison-list__item.bh.js"));
require("../../blocks.05-project/comparison-list/__item/comparison-list__item.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/slider-comparison/__feature/slider-comparison__feature.bh.js"));
require("../../blocks.05-project/slider-comparison/__feature/slider-comparison__feature.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/slider-comparison/__remove/slider-comparison__remove.bh.js"));
require("../../blocks.05-project/slider-comparison/__remove/slider-comparison__remove.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/slider-comparison/__item/slider-comparison__item.bh.js"));
require("../../blocks.05-project/slider-comparison/__item/slider-comparison__item.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/comparison-small-list/__link/comparison-small-list__link.bh.js"));
require("../../blocks.05-project/comparison-small-list/__link/comparison-small-list__link.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/comparison-small-item/comparison-small-item.bh.js"));
require("../../blocks.05-project/comparison-small-item/comparison-small-item.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/comparison-small-item/__remove/comparison-small-item__remove.bh.js"));
require("../../blocks.05-project/comparison-small-item/__remove/comparison-small-item__remove.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/comparison-small-list/__value/comparison-small-list__value.bh.js"));
require("../../blocks.05-project/comparison-small-list/__value/comparison-small-list__value.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/comparison-small-list/__remove/comparison-small-list__remove.bh.js"));
require("../../blocks.05-project/comparison-small-list/__remove/comparison-small-list__remove.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/footer-list/__item/footer-list__item.bh.js"));
require("../../blocks.05-project/footer-list/__item/footer-list__item.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/footer-list/__link/footer-list__link.bh.js"));
require("../../blocks.05-project/footer-list/__link/footer-list__link.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/soc/__item/soc__item.bh.js"));
require("../../blocks.04-common/soc/__item/soc__item.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/subscription/subscription.bh.js"));
require("../../blocks.04-common/subscription/subscription.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/radio/__control/radio__control.bh.js"));
require("../../blocks.04-common/radio/__control/radio__control.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/radio/__label/radio__label.bh.js"));
require("../../blocks.04-common/radio/__label/radio__label.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.03-fonts/custom-fonts/custom-fonts.bh.js"));
require("../../blocks.03-fonts/custom-fonts/custom-fonts.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.03-fonts/fa/fa.bh.js"));
require("../../blocks.03-fonts/fa/fa.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/fa/fa.bh.js"));
require("../../blocks.04-common/fa/fa.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/search-popover/search-popover.bh.js"));
require("../../blocks.05-project/search-popover/search-popover.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/container/container.bh.js"));
require("../../blocks.04-common/container/container.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/btn/btn.bh.js"));
require("../../blocks.04-common/btn/btn.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/btn/_block/btn_block.bh.js"));
require("../../blocks.04-common/btn/_block/btn_block.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/search-btn/search-btn.bh.js"));
require("../../blocks.05-project/search-btn/search-btn.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/breadcrumb/breadcrumb.bh.js"));
require("../../blocks.04-common/breadcrumb/breadcrumb.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/title-page/title-page.bh.js"));
require("../../blocks.05-project/title-page/title-page.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/select/select.bh.js"));
require("../../blocks.04-common/select/select.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/select/_chosen/select_chosen.bh.js"));
require("../../blocks.04-common/select/_chosen/select_chosen.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/select/_control/select_control.bh.js"));
require("../../blocks.04-common/select/_control/select_control.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/footer-list/footer-list.bh.js"));
require("../../blocks.05-project/footer-list/footer-list.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/radio/radio.bh.js"));
require("../../blocks.04-common/radio/radio.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.04-common/radio/_custom/radio_custom.bh.js"));
require("../../blocks.04-common/radio/_custom/radio_custom.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.01-base/page/page.bh.js"));
require("../../blocks.01-base/page/page.bh.js")(bh);
dropRequireCache(require, require.resolve("../../blocks.05-project/dropdown-menu/_ul/dropdown-menu_ul.bh.js"));
require("../../blocks.05-project/dropdown-menu/_ul/dropdown-menu_ul.bh.js")(bh);

module.exports = bh;
bh['bh'] = bh;